'use client';

import { useMemo, useState } from 'react';

type View = 'overview' | 'calendar' | 'appointments' | 'patients' | 'reports' | 'vaccines' | 'settings' | 'profile' | 'inspection';
type Appointment = { time:string; name:string; initials:string; age:string; phone:string; vaccine:string; dose:string; status:string; tone:string };

const appointments: Appointment[] = [
  { time:'09:00', name:'Малика Каримова', initials:'МК', age:'7 лет', phone:'+998 90 123 45 67', vaccine:'Инфлювак Тетра', dose:'1-я вакцинация', status:'Ожидает', tone:'blue' },
  { time:'09:45', name:'Давид Ли', initials:'ДЛ', age:'4 года', phone:'+998 93 234 56 78', vaccine:'Превенар 13', dose:'Ревакцинация', status:'Подтверждён', tone:'green' },
  { time:'10:30', name:'Алина Юсупова', initials:'АЮ', age:'12 лет', phone:'+998 95 345 67 89', vaccine:'Гардасил', dose:'2-я вакцинация', status:'На осмотре', tone:'purple' },
  { time:'11:15', name:'Тимур Ахмедов', initials:'ТА', age:'6 лет', phone:'+998 97 456 78 90', vaccine:'Гепатит A', dose:'1-я вакцинация', status:'Ожидает', tone:'blue' },
  { time:'12:00', name:'Самира Алиева', initials:'СА', age:'9 лет', phone:'+998 99 567 89 01', vaccine:'КПК', dose:'Ревакцинация', status:'Завершён', tone:'green' },
];

const patients = [
  ['Малика Каримова','7 лет','МК','+998 90 123 45 67','4 прививки','18.09.2026'],
  ['Давид Ли','4 года','ДЛ','+998 93 234 56 78','7 прививок','15.09.2026'],
  ['Алина Юсупова','12 лет','АЮ','+998 95 345 67 89','3 прививки','09.09.2026'],
  ['Тимур Ахмедов','6 лет','ТА','+998 97 456 78 90','5 прививок','02.09.2026'],
  ['Самира Алиева','9 лет','СА','+998 99 567 89 01','8 прививок','24.08.2026'],
];

const vaccines = [
  ['Инфлювак Тетра','Грипп','Нидерланды','L37F','250 000 сум','74'],
  ['Превенар 13','Пневмококк','США','NL 1050','480 000 сум','38'],
  ['Гардасил','ВПЧ','США','W003533','1 350 000 сум','21'],
  ['Гепатит A','Гепатит','Франция','R3K121V','320 000 сум','56'],
  ['Hexaxim','Комбинированная','Франция','X3G842V','450 000 сум','42'],
];

const nav: {id:View; icon:string; label:string}[] = [
  {id:'overview',icon:'⌂',label:'Обзор'}, {id:'calendar',icon:'▦',label:'Календарь'}, {id:'appointments',icon:'◷',label:'Приёмы'},
  {id:'patients',icon:'♙',label:'Пациенты'}, {id:'reports',icon:'▥',label:'Отчёты'}, {id:'vaccines',icon:'✦',label:'Вакцины'},
];

function Title({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode}) {
  return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subhead">{copy}</p></div>{action}</div>;
}

function Metric({tone,icon,label,value,detail}:{tone:string;icon:string;label:string;value:string;detail:string}) {
  return <article><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>;
}

function Appointments({onNew,onProfile,onInspection}:{onNew:()=>void;onProfile:()=>void;onInspection:()=>void}) {
  const [filter,setFilter] = useState('Все');
  const shown = filter==='Все' ? appointments.slice(0,4) : appointments.filter(a=>a.status.startsWith(filter)).slice(0,4);
  return <>
    <Title eyebrow="Понедельник, 21 сентября" title="Приёмы" copy="Управляйте расписанием и быстро переходите к осмотру." action={<button className="primary-button" onClick={onNew}><span>＋</span> Новый приём</button>} />
    <section className="metrics"><Metric tone="blue" icon="◷" label="Сегодня" value="24" detail="+3 к прошлому понедельнику"/><Metric tone="green" icon="✓" label="Завершено" value="8" detail="33% дневного плана"/><Metric tone="purple" icon="♙" label="Ожидают" value="12" detail="Ближайший через 14 минут"/><Metric tone="amber" icon="×" label="Отменено" value="4" detail="16% от всех приёмов"/></section>
    <section className="content-card"><div className="card-toolbar"><div className="view-tabs">{['Все','Ожидает','Завершён','Отменён'].map((f,i)=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{i===1?'Ожидают':i===2?'Завершены':i===3?'Отменены':'Все'} <span>{[24,12,8,4][i]}</span></button>)}</div><div className="toolbar-actions"><button className="secondary-button">▦&nbsp; Сегодня</button><button className="secondary-button">⚑&nbsp; Фильтры <i>2</i></button><button className="icon-button bordered">•••</button></div></div>
      <div className="table-head table-grid"><span>Время</span><span>Пациент</span><span>Вакцина</span><span>Статус</span><span/></div>{shown.map(a=><article className="appointment-row table-grid" key={a.time}><div className="time-cell"><strong>{a.time}</strong><small>30 мин</small></div><button className="patient-cell patient-button" onClick={onProfile}><span className={`patient-avatar ${a.tone}`}>{a.initials}</span><span><strong>{a.name}</strong><small>{a.age} · {a.phone}</small></span></button><div className="vaccine-cell"><strong>{a.vaccine}</strong><small>{a.dose}</small></div><div><span className={`status ${a.tone}`}><i/>{a.status}</span></div><div className="row-actions"><button className="examine-button" onClick={onInspection}>К осмотру</button><button className="plain-button">•••</button></div></article>)}
      <footer className="table-footer"><span>Показано {shown.length} из 24 приёмов</span><div><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></footer></section>
  </>;
}

function Overview({go}:{go:(v:View)=>void}) {
  return <><Title eyebrow="Понедельник, 21 сентября" title="Доброе утро, Азиза" copy="Коротко о работе центра сегодня." action={<button className="primary-button" onClick={()=>go('appointments')}><span>＋</span> Новый приём</button>}/><section className="metrics"><Metric tone="blue" icon="◷" label="Приёмов сегодня" value="24" detail="12 пациентов ожидают"/><Metric tone="green" icon="✓" label="Завершено" value="8" detail="Работа идёт по плану"/><Metric tone="purple" icon="♙" label="Новых пациентов" value="6" detail="За последние 7 дней"/><Metric tone="amber" icon="₸" label="Выручка" value="8,4 млн" detail="+12% к прошлой неделе"/></section><div className="dashboard-grid"><section className="content-card compact-card"><div className="section-head"><div><h2>Ближайшие приёмы</h2><p>Следующие два часа</p></div><button onClick={()=>go('appointments')}>Все приёмы →</button></div>{appointments.slice(0,4).map(a=><div className="mini-row" key={a.time}><strong>{a.time}</strong><span className={`patient-avatar ${a.tone}`}>{a.initials}</span><div><b>{a.name}</b><small>{a.vaccine}</small></div><span className={`status ${a.tone}`}><i/>{a.status}</span></div>)}</section><section className="content-card compact-card"><div className="section-head"><div><h2>Загрузка дня</h2><p>По часам</p></div><button>Неделя ⌄</button></div><div className="donut"><div><strong>67%</strong><span>заполнено</span></div></div><div className="legend"><span><i className="green-dot"/>Завершено <b>8</b></span><span><i className="blue-dot"/>Запланировано <b>12</b></span><span><i className="amber-dot"/>Свободно <b>6</b></span></div></section></div></>;
}

function Calendar({onNew,onInspection}:{onNew:()=>void;onInspection:()=>void}) {
  const days=['Пн 21','Вт 22','Ср 23','Чт 24','Пт 25','Сб 26'];
  return <><Title eyebrow="Расписание клиники" title="Календарь" copy="Неделя 21–26 сентября 2026." action={<button className="primary-button" onClick={onNew}><span>＋</span> Новый приём</button>}/><section className="content-card calendar-card"><div className="calendar-toolbar"><div><button>‹</button><button>›</button><button>Сегодня</button></div><h2>21–26 сентября</h2><div className="view-tabs"><button>День</button><button className="selected">Неделя</button><button>Месяц</button></div></div><div className="week-grid"><div className="time-axis"><span/><span>09:00</span><span>10:00</span><span>11:00</span><span>12:00</span><span>13:00</span></div>{days.map((d,di)=><div className="day-column" key={d}><strong className={di===0?'today':''}>{d}</strong>{di<4&&<><button className={`calendar-event ${di%2?'mint':'blue-event'}`} style={{top:`${54+di*34}px`}} onClick={onInspection}><b>{['09:00','09:30','10:15','10:45'][di]}</b><span>{appointments[di].name}</span><small>{appointments[di].vaccine}</small></button><button className="calendar-event violet" style={{top:`${174+di*18}px`}} onClick={onInspection}><b>{['11:00','11:30','12:00','12:30'][di]}</b><span>{appointments[(di+1)%4].name}</span><small>Осмотр</small></button></>}</div>)}</div></section></>;
}

function Patients({onProfile,onNew}:{onProfile:()=>void;onNew:()=>void}) {
  return <><Title eyebrow="База клиники" title="Пациенты" copy="Карточки, контакты и история вакцинации." action={<button className="primary-button" onClick={onNew}><span>＋</span> Новый пациент</button>}/><section className="metrics slim"><Metric tone="blue" icon="♙" label="Всего пациентов" value="9 475" detail="+62 за этот месяц"/><Metric tone="green" icon="✓" label="Активные" value="8 921" detail="94% общей базы"/><Metric tone="purple" icon="◫" label="Дети" value="7 304" detail="77% общей базы"/><Metric tone="amber" icon="!" label="Нужен повтор" value="186" detail="Просрочена вакцинация"/></section><section className="content-card"><div className="list-toolbar"><label className="inline-search">⌕<input placeholder="Поиск по имени или телефону"/></label><div><button className="secondary-button">Город: Все ⌄</button><button className="secondary-button">⚑ Фильтры</button></div></div><div className="patient-table-head patient-grid"><span>Пациент</span><span>Контакты</span><span>История</span><span>Последний визит</span><span/></div>{patients.map((p,i)=><div className="patient-list-row patient-grid" key={p[0]}><button className="patient-cell patient-button" onClick={onProfile}><span className={`patient-avatar ${['blue','green','purple','blue','green'][i]}`}>{p[2]}</span><span><strong>{p[0]}</strong><small>ID #{2400+i} · {p[1]}</small></span></button><span>{p[3]}</span><b>{p[4]}</b><span>{p[5]}</span><button className="plain-button">•••</button></div>)}</section></>;
}

function Reports() {
  const bars=[42,68,51,83,64,92,76];
  return <><Title eyebrow="Аналитика центра" title="Отчёты" copy="Вакцинации, выручка и география пациентов." action={<button className="secondary-button">⇩ Экспорт отчёта</button>}/><div className="report-filter"><div><label>Период</label><button>01.09.2026 — 21.09.2026</button></div><div><label>Вакцина</label><button>Все вакцины ⌄</button></div><div><label>Район</label><button>Все районы ⌄</button></div><button className="primary-button">Показать</button></div><section className="metrics"><Metric tone="blue" icon="◷" label="Всего приёмов" value="486" detail="+8,4% к прошлому периоду"/><Metric tone="green" icon="✓" label="Вакцинаций" value="421" detail="86,6% всех приёмов"/><Metric tone="purple" icon="₸" label="Выручка" value="118,6 млн" detail="Средний чек 282 000"/><Metric tone="amber" icon="×" label="Отмен" value="28" detail="5,8% всех записей"/></section><div className="dashboard-grid reports-grid"><section className="content-card chart-card"><div className="section-head"><div><h2>Динамика вакцинаций</h2><p>По дням недели</p></div><span className="trend">↗ +8,4%</span></div><div className="bar-chart">{bars.map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][i]}</small></div>)}</div></section><section className="content-card chart-card"><div className="section-head"><div><h2>Популярные вакцины</h2><p>Количество процедур</p></div></div>{[['Hexaxim','104','82%'],['Инфлювак Тетра','86','68%'],['Гепатит A','72','57%'],['Превенар 13','64','51%']].map(v=><div className="progress-row" key={v[0]}><div><b>{v[0]}</b><span>{v[1]}</span></div><i><em style={{width:v[2]}}/></i></div>)}</section></div></>;
}

function Vaccines({onNew}:{onNew:()=>void}) {
  return <><Title eyebrow="Справочник" title="Вакцины" copy="Препараты, серии, цены и остатки." action={<button className="primary-button" onClick={onNew}><span>＋</span> Добавить вакцину</button>}/><section className="metrics slim"><Metric tone="blue" icon="✦" label="Позиций" value="68" detail="12 групп препаратов"/><Metric tone="green" icon="□" label="В наличии" value="1 284" detail="Суммарный остаток"/><Metric tone="purple" icon="↗" label="Использовано" value="421" detail="За текущий месяц"/><Metric tone="amber" icon="!" label="Заканчиваются" value="5" detail="Меньше 10 доз"/></section><section className="content-card"><div className="list-toolbar"><label className="inline-search">⌕<input placeholder="Поиск вакцины, серии или страны"/></label><div><button className="secondary-button">Группа: Все ⌄</button><button className="secondary-button">Страна: Все ⌄</button></div></div><div className="vaccine-table-head vaccine-grid"><span>Наименование</span><span>Группа</span><span>Страна / серия</span><span>Цена</span><span>Остаток</span><span/></div>{vaccines.map(v=><div className="vaccine-list-row vaccine-grid" key={v[0]}><div className="vaccine-name"><span>{v[0][0]}</span><strong>{v[0]}</strong></div><span>{v[1]}</span><span>{v[2]}<small>{v[3]}</small></span><b>{v[4]}</b><span className={Number(v[5])<30?'low-stock':''}>{v[5]} доз</span><button className="plain-button">•••</button></div>)}</section></>;
}

function Profile({back,onInspection}:{back:()=>void;onInspection:()=>void}) {
  return <><button className="back-button" onClick={back}>← К пациентам</button><div className="profile-hero"><span className="large-avatar">МК</span><div><p>Пациент #2400</p><h1>Малика Каримова</h1><span>7 лет · Ташкент, Юнусабадский район</span></div><button className="secondary-button">✎ Изменить</button><button className="primary-button" onClick={onInspection}>Начать осмотр</button></div><div className="profile-layout"><section className="content-card detail-card"><div className="section-head"><div><h2>Контактная информация</h2><p>Основные данные пациента</p></div></div><dl className="details"><div><dt>Дата рождения</dt><dd>12 марта 2019</dd></div><div><dt>Телефон</dt><dd>+998 90 123 45 67</dd></div><div><dt>ФИО родителя</dt><dd>Сабина Каримова</dd></div><div><dt>Адрес</dt><dd>Ташкент, Юнусабадский район</dd></div><div><dt>Учреждение</dt><dd>Школа № 42</dd></div><div><dt>Источник</dt><dd>Рекомендация знакомых</dd></div></dl></section><section className="content-card passport-card"><div className="section-head"><div><h2>Паспорт вакцинации</h2><p>4 выполненные процедуры</p></div><button>Печать</button></div>{[['18.09.2026','Инфлювак Тетра','1-я вакцинация'],['04.03.2026','Гепатит A','2-я вакцинация'],['12.08.2025','Hexaxim','Ревакцинация'],['17.02.2025','КПК','1-я вакцинация']].map((x,i)=><div className="history-item" key={x[0]}><i className={i===0?'current':''}/><span><b>{x[1]}</b><small>{x[2]} · серия {['L37F','R3K121V','X3G842V','0132N005'][i]}</small></span><time>{x[0]}</time></div>)}</section></div></>;
}

function Inspection({back}:{back:()=>void}) {
  const groups: [string, string[]][]=[['Кожа',['Чистая','Бледно-розовая','Желтушная','Сыпь']],['Зев',['Спокойный','Гиперемирован']],['Миндалины',['Не гипертрофированы','Гипертрофированы']],['Лёгкие / дыхание',['Везикулярное','Жёсткое','Хрипы']],['Печень',['Не увеличена','Увеличена']],['Общее состояние',['Удовлетворительное','Неудовлетворительное']]];
  return <><button className="back-button" onClick={back}>← К приёмам</button><Title eyebrow="Пациент · Малика Каримова" title="Предвакцинальный осмотр" copy="Заполните показатели и примите решение о допуске."/><div className="inspection-layout"><section className="content-card inspection-form"><h2>Объективный осмотр</h2><div className="exam-groups">{groups.map((g,gi)=><fieldset key={g[0]}><legend>{g[0]}</legend><div>{g[1].map((o,oi)=><label key={o}><input type="radio" name={`g${gi}`} defaultChecked={oi===0}/><span>{o}</span></label>)}</div></fieldset>)}</div><h2>Показатели и заключение</h2><div className="vitals"><label>ЧД<input placeholder="20"/><small>в минуту</small></label><label>ЧСС<input placeholder="82"/><small>в минуту</small></label><label>Температура<input placeholder="36.6"/><small>°C</small></label></div><label className="text-field">Жалобы<textarea placeholder="Опишите жалобы пациента или укажите, что их нет"/></label><label className="text-field">Диагноз<textarea placeholder="Заключение врача"/></label></section><aside className="content-card decision-card"><h2>Решение врача</h2><p>Проверьте заполненные данные перед завершением.</p><label className="decision-option approved"><input type="radio" name="decision" defaultChecked/><span><b>Допущен</b><small>Вакцинация разрешена</small></span></label><label className="decision-option denied"><input type="radio" name="decision"/><span><b>Не допущен</b><small>Указать причину отказа</small></span></label><div className="decision-summary"><span>Вакцина</span><b>Инфлювак Тетра</b><span>Тип иммунизации</span><b>1-я вакцинация</b></div><button className="primary-button full" onClick={back}>Завершить осмотр</button><button className="secondary-button full">Сохранить черновик</button></aside></div></>;
}

function Settings() { return <><Title eyebrow="Управление" title="Настройки" copy="Параметры клиники и рабочего пространства."/><div className="settings-layout"><aside className="content-card settings-menu"><button className="selected">Общие</button><button>Расписание</button><button>Пользователи</button><button>Уведомления</button><button>Документы</button></aside><section className="content-card settings-form"><h2>Данные клиники</h2><div className="form-grid"><label>Название<input defaultValue="Клиника Novotek"/></label><label>Телефон<input defaultValue="+998 71 200 20 20"/></label><label>Email<input defaultValue="info@novotek.uz"/></label><label>Город<select defaultValue="t"><option value="t">Ташкент</option></select></label><label className="wide">Адрес<input defaultValue="Юнусабадский район, ул. Амира Темура, 108"/></label><label>Начало рабочего дня<input type="time" defaultValue="08:00"/></label><label>Конец рабочего дня<input type="time" defaultValue="18:00"/></label></div><div className="form-actions"><button className="secondary-button">Отмена</button><button className="primary-button">Сохранить изменения</button></div></section></div></> }

function Modal({type,onClose,onSwitch}:{type:'appointment'|'patient'|'vaccine';onClose:()=>void;onSwitch?:()=>void}) {
  const content = type==='appointment' ? {title:'Новый приём',copy:'Запланируйте визит пациента.',fields:['Пациент','Дата приёма','Время','Вакцина','Заметка']} : type==='patient' ? {title:'Новый пациент',copy:'Добавьте пациента в базу клиники.',fields:['Имя','Фамилия','Дата рождения','Телефон','Email','ФИО родителя','Адрес','Район']} : {title:'Новая вакцина',copy:'Добавьте препарат в справочник.',fields:['Наименование','Группа','Страна производства','Серия','Цена','Доза','Метод введения','Место введения']};
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal-card" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>{content.title}</h2><p>{content.copy}</p><div className="modal-form">{content.fields.map((f,i)=><label key={f} className={(type!=='appointment'&&i>4)?'wide':''}>{f}{f==='Заметка'?<textarea placeholder="Дополнительная информация"/>:f.includes('Дата')?<input type="date"/>:f==='Время'?<input type="time"/>:f==='Район'||f==='Группа'||f==='Страна производства'||f==='Вакцина'?<select><option>Выберите значение</option></select>:<input placeholder={`Введите: ${f.toLowerCase()}`}/>}</label>)}</div>{type==='appointment'&&<button className="add-inline" onClick={onSwitch}>＋ Добавить нового пациента</button>}<footer><button className="secondary-button" onClick={onClose}>Отмена</button><button className="primary-button" onClick={onClose}>Добавить</button></footer></section></div>;
}

export default function VaccineApp() {
  const [view,setView] = useState<View>('appointments');
  const [previous,setPrevious] = useState<View>('appointments');
  const [modal,setModal] = useState<null|'appointment'|'patient'|'vaccine'>(null);
  const title = useMemo(()=>nav.find(n=>n.id===view)?.label || (view==='profile'?'Карточка пациента':view==='inspection'?'Осмотр':'Настройки'),[view]);
  const go=(v:View)=>{ setPrevious(view); setView(v); window.scrollTo({top:0,behavior:'smooth'}); };
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">+</span><span><strong>Novotek</strong><small>Vaccination Center</small></span></div><nav><p className="nav-label">Рабочее пространство</p>{nav.map(n=><button key={n.id} className={`nav-item ${view===n.id?'active':''}`} onClick={()=>go(n.id)}><span>{n.icon}</span>{n.label}{n.id==='appointments'&&<b>12</b>}</button>)}<p className="nav-label nav-label-secondary">Управление</p><button className={`nav-item ${view==='settings'?'active':''}`} onClick={()=>go('settings')}><span>⚙</span>Настройки</button></nav><div className="clinic-card"><span className="clinic-icon">N</span><span><strong>Клиника Novotek</strong><small>Ташкент · открыт</small></span><button>⌄</button></div></aside><section className="workspace"><header className="topbar"><div className="mobile-logo"><span className="brand-mark">+</span> Novotek</div><label className="global-search"><span>⌕</span><input placeholder="Найти пациента, приём или вакцину"/><kbd>⌘ K</kbd></label><span className="current-section">{title}</span><div className="profile-actions"><button className="icon-button">♢<i/></button><span className="avatar">АШ</span><span className="profile-copy"><strong>Азиза Шарипова</strong><small>Администратор</small></span><button className="plain-button">⌄</button></div></header><div className="page">{view==='overview'&&<Overview go={go}/>} {view==='calendar'&&<Calendar onNew={()=>setModal('appointment')} onInspection={()=>go('inspection')}/>} {view==='appointments'&&<Appointments onNew={()=>setModal('appointment')} onProfile={()=>go('profile')} onInspection={()=>go('inspection')}/>} {view==='patients'&&<Patients onProfile={()=>go('profile')} onNew={()=>setModal('patient')}/>} {view==='reports'&&<Reports/>} {view==='vaccines'&&<Vaccines onNew={()=>setModal('vaccine')}/>} {view==='profile'&&<Profile back={()=>go(previous==='inspection'?'appointments':previous)} onInspection={()=>go('inspection')}/>} {view==='inspection'&&<Inspection back={()=>go('appointments')}/>} {view==='settings'&&<Settings/>}</div></section>{modal&&<Modal type={modal} onClose={()=>setModal(null)} onSwitch={()=>setModal('patient')}/>}</main>;
}
